<?php

function custom_functions_node_view($node, $view_mode, $langcode) {
    $search_url = $_SERVER['HTTP_REFERER'];
    $parse_url = parse_url($search_url);    
    // Extract term from the URL
    $extractsearchTerm = substr($parse_url['query'], strpos($parse_url['query'], "=") + 1);
    // Search Replace searched term in fields
    // Contents
    $node->field_contents['und'][0]['value'] = str_ireplace($extractsearchTerm,'<span style="color:red;">'.$extractsearchTerm.'</span>',$node->field_contents['und'][0]['value']); 
    // Finding Aids
    $node->field_finding_aids['und'][0]['value'] = str_ireplace($extractsearchTerm,'<span style="color:red;">'.$extractsearchTerm.'</span>',$node->field_finding_aids['und'][0]['value']);
    // Background Info
    $node->field_background_information['und'][0]['value'] = str_ireplace($extractsearchTerm,'<span style="color:red;">'.$extractsearchTerm.'</span>',$node->field_background_information['und'][0]['value']);
    // Notes
    $node->field_notes['und'][0]['value'] = str_ireplace($extractsearchTerm,'<span style="color:red;">'.$extractsearchTerm.'</span>',$node->field_notes['und'][0]['value']);
}

function _attach_files_loyalist(){
    // For Node type record
    $type = "loyalist_record"; 
    // Load nodes
    $loyalistnodes = node_load_multiple(array(), array('type' => $type)); 
    
    foreach($loyalistnodes as $individualloyalistnode){
            // Does the Node have an accompanying record
            if(isset($individualloyalistnode->field_accompanying_record['und'][0]['value']))
            {
               // Get the accompanying record value
               $finding_aid_acc =  $individualloyalistnode->field_accompanying_record['und'][0]['value'];
               // Local Finding Aids path
               $localfindaidsfolder = "/home/vagrant/finding_aids";
               $scanlocalfolder = scandir($localfindaidsfolder);
               foreach ($scanlocalfolder as $filename)
               {
                   if($filename == $finding_aid_acc.".pdf" || $filename == $finding_aid_acc.".txt" || $filename == $finding_aid_acc.".html")
                   {
                       // Basename
                       $fn = basename($filename);
                       $file_drupal_path = "/vagrant/public/drupal.vbox.local/www/sites/default/files/finding_aids_docs/".$fn;
                       // Copy local folder files to Drupal
                       $cp = copy($localfindaidsfolder.'/'.$filename,$file_drupal_path);
                       // While at copying build a file object for each of those imports
                       if($cp) {
                        // File Object Properties
                        $findingaidfile = new stdClass();
                        $findingaidfile->filename  = basename($file_drupal_path);
                        $findingaidfile->filepath  = $_SERVER['DOCUMENT_ROOT'].'/sites/default/files/finding_aids_docs/'.$fn;
                        $findingaidfile->uri       = 'public://finding_aids_docs/'.$findingaidfile->filename;
                        $findingaidfile->filemime  = mime_content_type($file_drupal_path);
                        $findingaidfile->filesize  = filesize($file_drupal_path);
                        $findingaidfile->uid       = 1;
                        $findingaidfile->timestamp = time();
                        $findingaidfile->status = FILE_STATUS_PERMANENT;
                        $findingaidfile->display = 1;
                        // Add file object to Drupal Schema
                        drupal_write_record('file_managed', $findingaidfile);
                        }
                    }
                }
                // Add File object to node field
                $individualloyalistnode->field_finding_aid_record['und'][0] = (array)$findingaidfile;
                // Save the node
                node_save($individualloyalistnode);
            }
       }
}

function custom_functions_preprocess_views_view(&$vars) {
   $view = $vars['view'];
   // Make sure it's the correct view
   if($view->name == 'search_loyalists') {
     // add needed javascript
     drupal_add_js(drupal_get_path('module', 'loyalist_insert') . '/highlight_terms.js');
     drupal_add_js(drupal_get_path('module', 'loyalist_insert') . '/jquery.highlight-4.js');
     // add needed stylesheet
     drupal_add_css(drupal_get_path('module', 'loyalist_insert') .'/loyalist_insert.css');
  }
}

